### ISSUE TITLE
Bug or float equals problem?

### ISSUE THREAD

**Issue by zhaishengfu** [CaptainProton42/2DGrassShaderDemo#1] opened 2020-11-01 09:55 UTC
Wonderful project. I always think using shader to do dynamic grass, this give me good ideas. When i follow your instructions, i found one problem:
![image](https://user-images.githubusercontent.com/7630101/97799748-d45e6800-1c6a-11eb-8dbe-095cb44f9802.png)
you use float equals, and i find this is not safe. if use 
if dist / 255.0 == texture(tex, uv).r
the result will be wrong
![image](https://user-images.githubusercontent.com/7630101/97799826-2c956a00-1c6b-11eb-8b38-973416b45dca.png)
and use
if (abs(dist / 255.0 - texture(tex, uv).r) < 0.0000001), the result will be correct. Maybe for float, use equal is not safe

**Comment by CaptainProton42** [comment] 2020-11-01 10:20
You are absolutely right, this seems to be caused by a rounding error.

Comparing with an epsilon value like you did is much safer. Alternatively, if you don't care about web export etc. you could also use GLES3 and integer datatypes.

This should be fixed now.

**Closed as completed** 2020-11-01 10:20 UTC
